"""
=== STEGVERSE FILE METADATA ===
sv_file: scw/scw_core.py
sv_kind: python
sv_module: SCW
sv_version: 4.0.0
sv_build_id: 20251125-000000Z
sv_epoch: 9
sv_parent_build: 20251124-000000Z
sv_hash: auto
sv_sig: svmeta:v1
=== END STEGVERSE FILE METADATA ===

SCW Core (v4)

Commands:
- org-scan: produce reports/org_scan.json + fix queue
- autopatch: apply pending structure fixes repo-by-repo
- doctor: local sanity checks

v4 upgrades:
- queue-first autopatch
- pending-perms retry (does not demand token maintenance)
"""

from __future__ import annotations

import os, json, subprocess, pathlib, datetime as dt
from typing import Dict, Any, List
import yaml
import requests

from .org_health import scan_org, load_policy

API = "https://api.github.com"

def log(msg): print(f"[SCW_CORE] {msg}", flush=True)

def gh_headers(token:str)->dict:
    return {"Authorization": f"Bearer {token}",
            "Accept":"application/vnd.github+json",
            "User-Agent":"StegVerse-SCW-v4"}

def gh_get(token, path, params=None):
    r = requests.get(f"{API}{path}", headers=gh_headers(token), params=params, timeout=30)
    if r.status_code >= 300:
        raise RuntimeError(f"GitHub GET {path} failed: {r.status_code} {r.text[:200]}")
    return r.json()

def run(cmd:List[str], cwd=None):
    log(" ".join(cmd))
    return subprocess.run(cmd, cwd=cwd, check=False, text=True, capture_output=True)

def ensure_repo_checkout(tmpdir: pathlib.Path, full_name:str, token:str, ref="main")->pathlib.Path:
    owner, repo = full_name.split("/")
    url = f"https://x-access-token:{token}@github.com/{owner}/{repo}.git"
    target = tmpdir / repo
    if target.exists():
        run(["git","fetch","--all"], cwd=target)
        run(["git","reset","--hard", f"origin/{ref}"], cwd=target)
    else:
        run(["git","clone","--depth","1","--branch",ref,url,str(target)])
    return target

def apply_structure_fix(repo_path: pathlib.Path, item: dict, policy: dict) -> bool:
    """
    v4 minimal: only ensures required SCW workflow files exist.
    Real template rendering lives in SCW bundle templates.
    """
    path = item["path"]
    wanted_ver = item.get("wanted_version","4.0.0")

    # If file missing or stale, we copy from SCW repo templates if present.
    # Fallback: do nothing but keep queue (safe).
    template_src = pathlib.Path(os.getenv("GITHUB_WORKSPACE",".")) / path
    dest = repo_path / path
    dest.parent.mkdir(parents=True, exist_ok=True)

    if template_src.exists():
        dest.write_text(template_src.read_text(), encoding="utf-8")
        log(f"Applied template {path}")
        return True

    log(f"No template found for {path}; leaving pending.")
    return False

def autopatch(fix_queue: dict, policy: dict):
    token = os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN")
    if not token:
        raise SystemExit("Missing GH_TOKEN")

    tmpdir = pathlib.Path("/tmp/scw_autopatch")
    tmpdir.mkdir(parents=True, exist_ok=True)

    items = sorted(fix_queue.get("items",[]), key=lambda x: -float(x.get("risk_score",0.0)))

    for item in items:
        if item["status"] in ("done","triage"): 
            continue
        if item["action"] not in ("add","replace"):
            continue

        repo = item["repo"]
        ref = "main"
        try:
            ref = gh_get(token, f"/repos/{repo}")["default_branch"]
        except Exception:
            pass

        repo_path = ensure_repo_checkout(tmpdir, repo, token, ref)
        ok = apply_structure_fix(repo_path, item, policy)
        if not ok:
            item["status"] = "pending"
            continue

        # Commit on branch
        branch = f"healthfix/{dt.datetime.utcnow().strftime('%Y%m%d-%H%M%S')}"

        run(["git","checkout","-b",branch], cwd=repo_path)
        run(["git","add", item["path"]], cwd=repo_path)

        c = run(["git","commit","-m",f"scw: {item['action']} {item['path']}"], cwd=repo_path)
        if c.returncode != 0:
            item["status"] = "pending"
            continue

        p = run(["git","push","-u","origin",branch], cwd=repo_path)
        if p.returncode != 0:
            item["status"] = "pending-perms"
            item["last_attempt_utc"] = dt.datetime.utcnow().isoformat()+"Z"
            continue

        # If push ok, open PR
        try:
            owner, name = repo.split("/")
            pr = requests.post(
                f"{API}/repos/{owner}/{name}/pulls",
                headers=gh_headers(token),
                json={
                    "title": f"SCW autofix: {item['path']}",
                    "head": branch,
                    "base": ref,
                    "body": f"Auto-generated by SCW v4. Reason: {item['reason']}"
                },
                timeout=30
            )
            if pr.status_code >= 300:
                item["status"] = "pending-perms"
            else:
                item["status"] = "done"
        except Exception:
            item["status"] = "pending"

        item["last_attempt_utc"] = dt.datetime.utcnow().isoformat()+"Z"

def main():
    root = pathlib.Path(os.getenv("GITHUB_WORKSPACE","."))
    cmd = os.getenv("SCW_CMD","org-scan").strip()
    token = os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN")
    if not token:
        raise SystemExit("Missing GH_TOKEN")

    policy = load_policy(root)
    orgs = os.getenv("SCW_ORGS","StegVerse,StegVerse-Labs").split(",")

    if cmd == "org-scan":
        report = scan_org(token, [o.strip() for o in orgs if o.strip()], policy)
        (root/"reports").mkdir(exist_ok=True)
        (root/"reports"/"org_scan.json").write_text(json.dumps(report, indent=2))
        log("org-scan complete")
        return

    if cmd == "autopatch":
        report_path = root/"reports"/"org_scan.json"
        if not report_path.exists():
            raise SystemExit("No reports/org_scan.json; run org-scan first.")
        report = json.loads(report_path.read_text())
        autopatch(report.get("fix_queue",{}), policy)
        report_path.write_text(json.dumps(report, indent=2))
        log("autopatch complete")
        return

    if cmd == "doctor":
        log("doctor: ok (v4)")
        return

    raise SystemExit(f"Unknown SCW_CMD={cmd}")

if __name__ == "__main__":
    main()
